name: Build, test, and publish Docker image

on:
  push:
    branches: [ 'main' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: "update: build and test embedding-server image"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: install nix
        uses: cachix/install-nix-action@v20
        with:
          install_url: https://releases.nixos.org/nix/nix-2.15.0/install
          extra_nix_config: |
            experimental-features = nix-command flakes recursive-nix ca-derivations impure-derivations
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: nix build .#docker-image -L

      - name: Save and tag image
        run: |
          set -x
          docker load -i ./result
          docker tag embedding-server:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA}
          docker tag embedding-server:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Log in to the Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to the Container registry
        run: |
          set -x
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
